sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: NtiTvfUOce264fVoAeDpdSKCql3rJ6H20HcNwbeR3l3mWl8prhsNaq4Q4caqI7xukXrho0+i5y+B+SbfZ//3Sxu9B2BjiQKoqGqggOllof5aDq9Yku+r+vMiHC9Mp3KkB9tYmzteJukHyOEs9Qilg+tiw5NRLl1fZESkjmNE7MY7mLRGUq7ODN7uynKJZhDF6D7d8yYxviUpTI/mIGPV86ZtvmqqIsY7AB9CnPfWPtMFS8UnyHvS1OccQ7c2smOiufOFjqIwoJssmFlTlI3wyPcQeU/jiJFi1ZwmZPQOek0xT3vZWJ43g31KMkBXXu3Z0ZHNkIPyLEiZu+zrqcNpnb8qu3OBX35tucPVQje6YqWZ7GUVPGH9bjFrXG0BWpItBR/JTdKPDTtQMHHqDsLMFaYOkszlBX79Xs8M1stwAYFvL/dfdV8jgh5FTiqm73mSJ/TCTzVMfm+DeFsvWbONcX7Du0N5/dPnnmna+yT2xuhGbqbRC9v+P/ah7IUkTE20mCEfBmGKL2vVu0jPEN2l8K2GX/5L0Ybh+swo7ywQxK423v69kQYdKzq33K/t5fdDzARAPN7LOQykJOBxziQ1p+YdT57BXl3AUacca02wwo21NtTO+4V1x70tKH4Honc/lpYIWafidazg3tbliBWlZ1GZyX86tqGDACXhaMBrLJ0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Cymbeline_1538
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy